[build]
command = "hugo --gc"
publish = "public"

[[headers]]
for = "/fonts/*"

[headers.values]
Cache-Control = "public, s-maxage=31536000, immutable"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, s-maxage=31536000, immutable"

[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.143.1"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.143.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.143.1"

[[redirects]]
from = "/main.min.css"
to = "/main.min.css"
status = 200
force = true

[[redirects]]
from = "/images/stand-with-ukraine.svg"
to = "/images/stand-with-ukraine.svg"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/stand-with-ukraine/"
status = 301
force = true
conditions = { Country = ["RU"] }
